apiVersion: v1
kind: Pod
metadata:
  name: test_configmap
spec:
  containers:
    - name: test-container
      image: aranaivo/myphpapp
      command: ["/bin/sh", "-c", "echo ENV NAME: $(ENVNAME) LOGIN: $(LOGIN) PASSWORD: $(PWD)"]
      env:
        - name: ENVNAME
          valueFrom:
            configMapKeyRef:
              name: prod-env
              key: envname
         - name: LOGIN
           valueFrom:
             secretKeyRef:
               name: mysecretprod
               key: username
         - name: PWD
           valueFrom:
             secretKeyRef:
               name: mysecretprod
               key: password
  restartPolicy: Never
