apiVersion: v1
kind: Service
metadata:
  name: myapp-prod
  namespace: prod
  labels:
    app: my-app-prod
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31001
  selector:
    app: my-app-prod
